'bc': bc/*
'bug :bug:': bug/*
'chore :hammer:': chore/*
'ci :gear:': ci/*
'dependancies :robot:': dependancies/*
'documentation :books:': ['doc/*', 'docs/*', 'documentation/*']
'feature :heavy_plus_sign:': ['feature/*', 'feat/*']
'fix :bug:': fix/*
'hotfix :fire_engine:': hotfix/*
'perf': perf/*
'refactor :nut_and_bolt:': ['refactor/*', 'refacto/*']
'review': review/*
'security': security/*
'style': style/*
'test': test/*
