services:
  web:
    image: ghcr.io/aymericshini/portfolio:latest # Replace with Docker Hub or GitHub image
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
    restart: always # Ensure the service restarts in case of failures
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
